### ISSUE TITLE
CaasMapper provides unconsistent types for table cell colspan and rowspan

### ISSUE THREAD

**Issue by alexkoerner** [e-Spirit/fsxa-api#129] opened 2022-09-13 15:01 UTC
The structure for a table contains the type `number` in the colspan and in the rowspan key if the value is `1`. Otherwise the value is from type `string`.

**Comment by henczi-espirit** [comment] 2022-09-21 09:47
This issue seems to be related to #128.
We will treat both issues as one and update on the earlier report. 
>> closed

**Comment by henczi-espirit** [comment] 2022-09-28 07:23
It turns out that issue https://github.com/e-Spirit/fsxa-api/issues/128 and this one here are not related. @alexkoerner could you provide a reproduction for a scenario where this typing issue leads to a problem or is it a typing issue without any further impact?

**Comment by alexkoerner** [comment] 2022-09-28 07:43
I don't know what has been changed in the background, but the values are now typed correct as number.

**Comment by henczi-espirit** [comment] 2022-09-28 07:45
That is good. I will close the issue :-)

**Closed by henczi-espirit** 2022-09-28 07:45 UTC
